server_pubkey: JRN2ePnb9UYzrtf8TdOni50wyqj0ZJG+83wttILdny4=
server_privkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66303135643537363035633463333163623034386137353031653235333766613638306461323934
          3261653639656636326139316264323732306565393963360a613965393866383735313064623561
          34613337656239666265336238396537336137613733636334643066323466623732383632323433
          3435353333386133380a386162323961636365393739316164383932343762383131636465613433
          64363962613864643537373930616333393336333562343435623965353033396639626436393332
          6665636366656436646565306536303136623165313038386239